inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/**/*.rb'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 26

Metrics/AbcSize:
  Max: 41

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

DotPosition:
  Enabled: false

Style/StringLiterals:
  Enabled: false

LineLength:
  Max: 120

CyclomaticComplexity:
  Max: 12

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
