version: '3.7'

services:
  redis:
    image: redis:5.0.5-alpine
    command: redis-server
    volumes:
      - redis:/data

  web:
    depends_on:
      - redis
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-L', 'http://localhost:3000/hc']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sidekiq:
    depends_on:
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  redis:
  letsencrypt:
