send_message:
  cron:  '5 */2 * * *'
  class: 'Telegram::SendMessageToSubscribersWorker'

certbot_renew:
  cron:  '0 0 */15 * *'
  class: 'CertbotRenewWorker'

subscriptions_activate:
  cron: "*/5 * * * *"
  class: "Subscriptions::ActivateWorker"
