send_message:
  cron:  '5 7-19 * * *'
  class: 'Telegram::SendMessageToSubscribersWorker'

send_external_article:
  cron:  '0 7 * * *'
  class: 'Telegram::SendExternalArticleWorker'

certbot_renew:
  cron:  '0 0 */15 * *'
  class: 'CertbotRenewWorker'
