default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  paypal:
    base_url: '<%= ENV['PAYPAL_BASE_URL'] %>'
    client_id: '<%= ENV['PAYPAL_CLIENT_ID'] %>'
    secret: '<%= ENV['PAYPAL_SECRET'] %>'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
